"""add_payee_id_to_escrow

Revision ID: 217b9790c741
Revises: add_setu_fields
Create Date: 2025-11-26 10:30:01.968947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217b9790c741'
down_revision: Union[str, None] = 'add_setu_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrows', sa.Column('payee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'escrows', 'users', ['payee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.drop_column('escrows', 'payee_id')
    # ### end Alembic commands ###
