"""add_razorpay_payment_tracking

Revision ID: d58881f8361e
Revises: 
Create Date: 2025-11-18 06:07:58.706802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58881f8361e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_status', sa.String(length=50), nullable=False),
    sa.Column('razorpay_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('webhook_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('escrows', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('escrows', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.add_column('escrows', sa.Column('razorpay_payout_id', sa.String(length=100), nullable=True))
    op.add_column('escrows', sa.Column('razorpay_refund_id', sa.String(length=100), nullable=True))
    op.add_column('escrows', sa.Column('payment_initiated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('escrows', sa.Column('payment_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('escrows', sa.Column('payout_initiated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('escrows', sa.Column('payout_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('escrows', sa.Column('last_payment_error', sa.Text(), nullable=True))
    op.add_column('escrows', sa.Column('payment_retry_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('upi_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('upi_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bank_ifsc', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('bank_account_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_account_name')
    op.drop_column('users', 'bank_ifsc')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'upi_verified')
    op.drop_column('users', 'upi_id')
    op.drop_column('escrows', 'payment_retry_count')
    op.drop_column('escrows', 'last_payment_error')
    op.drop_column('escrows', 'payout_completed_at')
    op.drop_column('escrows', 'payout_initiated_at')
    op.drop_column('escrows', 'payment_completed_at')
    op.drop_column('escrows', 'payment_initiated_at')
    op.drop_column('escrows', 'razorpay_refund_id')
    op.drop_column('escrows', 'razorpay_payout_id')
    op.drop_column('escrows', 'razorpay_payment_id')
    op.drop_column('escrows', 'razorpay_order_id')
    op.drop_table('payment_logs')
    # ### end Alembic commands ###
