"""add_escrow_code_and_name_fields

Revision ID: f8497a805f5e
Revises: d58881f8361e
Create Date: 2025-11-22 12:38:48.602544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8497a805f5e'
down_revision: Union[str, None] = 'd58881f8361e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('escrows', sa.Column('escrow_code', sa.String(length=6), nullable=True))
    op.add_column('escrows', sa.Column('escrow_name', sa.String(length=100), nullable=True))
    op.add_column('escrows', sa.Column('is_code_active', sa.Boolean(), nullable=True))
    
    # Generate codes for existing escrows
    import random
    import string
    from sqlalchemy import text
    
    conn = op.get_bind()
    result = conn.execute(text("SELECT id FROM escrows WHERE escrow_code IS NULL"))
    escrow_names = [
        "Swift Eagle", "Golden Phoenix", "Silver Hawk", "Blue Falcon", "Red Dragon",
        "Green Tiger", "Purple Wolf", "Orange Lion", "Pink Panther", "Black Bear"
    ]
    
    for row in result:
        code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        name = random.choice(escrow_names)
        conn.execute(
            text("UPDATE escrows SET escrow_code = :code, escrow_name = :name, is_code_active = true WHERE id = :id"),
            {"code": code, "name": name, "id": row[0]}
        )
    
    # Now make escrow_code NOT NULL and add unique constraint
    op.alter_column('escrows', 'escrow_code', nullable=False)
    op.create_index(op.f('ix_escrows_escrow_code'), 'escrows', ['escrow_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escrows_escrow_code'), table_name='escrows')
    op.drop_column('escrows', 'is_code_active')
    op.drop_column('escrows', 'escrow_name')
    op.drop_column('escrows', 'escrow_code')
    # ### end Alembic commands ###
